Repository ContentsViewer/sh-tetris, pull requests merged in 2021-12, with the labels that each got.

#2 Set executable bit
  README.md
  tetris
Labels: enhancement

#12 Enable `--no-beep` (fix #10)
  tetris
Labels: bug

#11 Delete extra spaces
  tetris
Labels: enhancement

#4 Eliminate some command substitutions to improve performance
  tetris
Labels: enhancement

#5 Better key reading
  tetris
Labels: enhancement

#14 Improved compatibility with zsh and dash
  tetris
Labels: enhancement

#15 Refactor draw_help
  tetris
Labels: enhancement

#9 Fix README
  README.md
Labels: documentation

#3 Rewrite Bag System
  tetris
Labels: enhancement

#13 Added cleanup on CTRL-C exit
  tetris
Labels: bug

#16 Fix usage
  README.md
Labels: documentation

#24 Refactor for statement sending
  tetris
Labels: enhancement

#28 Handle process wait correctly
  tetris
Labels: bug

#29 The reader also needs to be terminated at the end of the game
  tetris
Labels: bug

#30 Fix program name in zsh
  tetris
Labels: bug

#53 Remove dependency on the clear command
  tetris
Labels: enhancement

#52 Suppresses unneeded ghost rendering
  tetris
Labels: enhancement

#48 Add logo above copyright
  tetris
Labels: enhancement
